services:
  server:
    image: hello-back-dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    container_name: todo-backend-dev
    depends_on:
      - redis
      - mongo
    environment: 
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongo:27017
  
  mongo:
    image: mongo:latest
    container_name: todo-mongo
    ports:
      - 27017:27017

    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo-data:/data/db
    restart: always
  redis:
    image: redis:latest
    container_name: todo-redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data  
    restart: always

volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local