# fly.toml app configuration file generated for pokedex-app-6035 on 2025-07-13T03:53:28+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pokedex-app-6035'
primary_region = 'sin'

[env]
  PORT = "5000"

[processes]
  app = "node app.js"

[build]

[deploy]
  strategy = "canary"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "90s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
