# fly.toml app configuration file generated for part11-silent-silence-5676 on 2025-07-13T01:51:35+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'part11-silent-silence-5676'
primary_region = 'cdg'

[build]

[processes]
  app = "node app.js"

[env]
  PORT = "5000"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
