services:
  app:
    image: hello-front-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 5173:5173
    container_name: hello-front-dev
    command: sh -c "npm install && npm run dev -- --host"
  debug-helper:
    image: busybox
    container_name: debug-helper