name: hello-world
on:
  push:
    branches:
      - part11-ci-cd-systems
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello, World!"
      - name: check date
        run: date
      - name: list files
        run: ls -la