name: Deployment Pipeline
on:
  push:
    branches:
      - part11-ci-cd-systems
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: part11-ci-cd-systems

      - name: cd to project directory
        run: cd part11
      # - name: List checked out files
      #   run: ls -al

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install
      - name: Check style
        run: npm run eslint